# stolen from https://grafana.com/docs/grafana-cloud/quickstart/docker-compose-linux/
# and from https://github.com/Einsteinish/Docker-Compose-Prometheus-and-Grafana/blob/master/docker-compose.yml
# https://stackoverflow.com/questions/54813704/how-to-add-dashboard-configuration-json-file-in-grafana-image

version: '3.8'

networks:
    monitor:
        driver: bridge

services:
    prometheus:
        image: prom/prometheus:latest
        user: "root:root"
        container_name: prometheus
        hostname: prometheus
        restart: unless-stopped
        volumes:
            - ./prometheus.yml:/etc/prometheus/prometheus.yml
            - ./prometheus_data:/prometheus
        command:
            - '--config.file=/etc/prometheus/prometheus.yml'
            - '--storage.tsdb.path=/prometheus'
            - '--web.console.libraries=/etc/prometheus/console_libraries'
            - '--web.console.templates=/etc/prometheus/consoles'
            - '--web.enable-lifecycle'
        expose:
            - "9090"
        networks:
            - monitor

    grafana:
        image: grafana/grafana:latest
        user: "root:root"
        container_name: grafana
        hostname: grafana
        volumes:
            - ./grafana_data:/var/lib/grafana
            - ./grafana/provisioning:/etc/grafana/provisioning
        restart: unless-stopped
        ports:
            - "3000:3000"
        networks:
            - monitor
